@NonCPS
def slackNotifier(String buildResult) {
  if ( buildResult == "SUCCESS" ) {
    slackSend ( color: "good",
    teamDomain: 'macmaceficios',
    tokenCredentialId: 'mac-slack',
    channel: '#financeiro_contabil-build',
    message: "Job: ${env.JOB_NAME} \nBuild: ${env.BUILD_NUMBER} \nStatus: Sucesso \nTempo: ${currentBuild.durationString.minus(' and counting')}")
  }
  else if( buildResult == "FAILURE" ) {
    slackSend( color: "danger",
    teamDomain: 'macmaceficios',
    tokenCredentialId: 'mac-slack',
    channel: '#financeiro_contabil-build',
    message: "Job: ${env.JOB_NAME} \nBuild: ${env.BUILD_NUMBER} \nStatus: Falha \nTempo: ${currentBuild.durationString.minus(' and counting')}")
  }
  else if( buildResult == "UNSTABLE" ) {
    slackSend( color: "warning",
      teamDomain: 'macmaceficios',
      tokenCredentialId: 'mac-slack',
      channel: '#financeiro_contabil-build',
      message: "Job: ${env.JOB_NAME} \nBuild: ${env.BUILD_NUMBER} \nStatus: Unstable \nTempo: ${currentBuild.durationString.minus(' and counting')}")
  }
  else if( buildResult == "ABORTED" ) {
    slackSend( teamDomain: 'macmaceficios',
      tokenCredentialId: 'mac-slack',
      channel: '#financeiro_contabil-build',
      message: "Job: ${env.JOB_NAME} \nBuild: ${env.BUILD_NUMBER} \nStatus: Abortado \nTempo: ${currentBuild.durationString.minus(' and counting')}")
  }
  else if( buildResult == "null" ) {
    slackSend( color: "warning",
      teamDomain: 'macmaceficios',
      tokenCredentialId: 'mac-slack',
      channel: '#financeiro_contabil-build',
      message: "Job: ${env.JOB_NAME} \nBuild: ${env.BUILD_NUMBER} \nStatus: Desconhecido \nTempo: ${currentBuild.durationString.minus(' and counting')}")
  }
}

def startMsg() {
  commit_desc = sh(script: "git log -1 --format='format:%s'", returnStdout: true).trim()
  slackSend(teamDomain: 'macmaceficios',
    tokenCredentialId: 'mac-slack',
    channel: '#financeiro_contabil-build',
    message: "Job: ${env.JOB_NAME} \nBuild: <${env.BUILD_URL}|build ${env.BUILD_DISPLAY_NAME}> \nIniciado por: ${env.BUILD_USER}\n Commit: ${commit_desc}\nBranch: ${env.BRANCH_NAME}")
}
@NonCPS
def configFromBranch(branch) {
    def env_dev = [
        rancherContext: 'c-lh4tc:p-58j5f',
        deploymentFile: 'deployment.yml',
        namespace: 'converter-dev'
    ]
    def env_staging = [
        rancherContext: 'c-lh4tc:p-58j5f',
        deploymentFile: 'deployment.yml',
        namespace: 'converter-stg'
    ]
    def env_prd = [
        rancherContext: '',
        deploymentFile: '',
        namespace: ''
    ]
    if (branch ==~ /(develop)/) { 
        return [
            shouldBuildImage: true,
            shouldPushImage: true,
            shouldDeploy: true,
            env: 'develop',
            tag: 'aws-dev',
            deployments: [env_dev]
        ]
    }
    else if (branch ==~ /(staging)/) {
        return [
            shouldBuildImage: true,
            shouldPushImage: true,
            shouldDeploy: true,
            env: 'staging',
            tag: 'aws-stg',
            deployments: [env_staging]
        ]
    }
    else if (branch ==~ /(master)/) {
        return [
            shouldBuildImage: true,
            shouldPushImage: true,
            shouldDeploy: false,
            env: 'production',
            tag: 'aws-prd',
            deployments: [env_prd]
        ]
    }
    else {
        return [
            shouldBuildImage: false,
            shouldPushImage: false,
            shouldDeploy: false,
            tag: '-',
            deployments: []
        ]
    }
}

pipeline {
    agent none
    
    environment {
        CONFIG = configFromBranch(BRANCH_NAME)
        SHOULD_BUILD_IMAGE = "${CONFIG.shouldBuildImage}"
        SHOULD_PUSH_IMAGE = "${CONFIG.shouldPushImage}"
        SHOULD_DEPLOY = "${CONFIG.shouldDeploy}"
        ENV = "${CONFIG.env}"
        NAME ="${CONFIG.namespace}"

        GIT_URL="git@bitbucket.org:macvisacard/avro-agendamento-pedido-converter.git"
        PROJECT_NAME="conv-agendamento-pedido"

        IMAGE_TAG = "${CONFIG.tag}-${env.BUILD_ID}"
        IMAGE_NAME = "${PROJECT_NAME}:${IMAGE_TAG}"
        IMAGE_URL = "123721783999.dkr.ecr.sa-east-1.amazonaws.com/${IMAGE_NAME}"
        IMAGE_URL_LATEST = "123721783999.dkr.ecr.sa-east-1.amazonaws.com/${PROJECT_NAME}:${CONFIG.tag}-latest"
    }
          
    stages {
        stage ('CD') {
            
            stages {
                stage ('Deploy') {
                    agent {
                        label 'Build'
                    }
                    stages{                                                                                                      
                        stage ('Docker - Build') {
                            when {
                              expression { SHOULD_BUILD_IMAGE == 'true' }
                            }                  
                            steps {
                                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'mac-ecr', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                                    sh "export AWS_DEFAULT_REGION=sa-east-1"
                                    sh "\$(/usr/local/bin/aws ecr get-login --no-include-email --region sa-east-1)"
                                    sh "docker build --pull -t ${IMAGE_URL} -t ${IMAGE_URL_LATEST} --no-cache ."
                                }
                            }
                        }
                        stage('Docker - Push'){
                            when {
                              expression { SHOULD_PUSH_IMAGE == 'true' }
                            }
                            steps{
                                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'mac-ecr', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                                    sh "docker push ${IMAGE_URL}"
                                    sh "docker push ${IMAGE_URL_LATEST}"
                                    echo "Image push complete"
                                }
                            }
                        }
                        stage('Sysdig Analysis - Scan'){
                            when {
                              expression { SHOULD_PUSH_IMAGE == 'true' }
                            }
                            steps{
                                sh "echo ${IMAGE_URL} > sysdig_secure_images"
                                sysdig engineCredentialsId: 'sysdig-token', name: 'sysdig_secure_images', inlineScanning: true, bailOnFail: true, bailOnPluginFail: true
                            }
                        }
                        stage('Kubernetes Deploy'){
                            when {
                              expression { SHOULD_DEPLOY == 'true' }
                            }                          
                            steps {
                                script {
                                    for (deployment in configFromBranch(BRANCH_NAME).deployments) {
                                        sh "echo yes | /usr/bin/rancher login --token token-lxxmp:some-entropy-token --context ${deployment.rancherContext} --name rancher2 https://ec2-18-228-89-100.sa-east-1.compute.amazonaws.com/v3"
                                        sh """
                                            sed '
                                              s,{{IMAGE_URL}},${IMAGE_URL},g;
                                              s,{{NAMESPACE}},${deployment.namespace},g;
                                              s,{{PROJECT_NAME}},${PROJECT_NAME},g;
                                            ' ${deployment.deploymentFile} | /usr/bin/rancher kubectl apply -f -
                                            """
                                     }
                                }
                             }
                         }
                    }
                }
            }
        }
    }
    post {
        success {
            script{
                slackNotifier('SUCCESS')
            }
        }
        failure{
            script{
                slackNotifier('FAILURE')
            }
        }
        unstable{
            script{
                slackNotifier('UNSTABLE')
            }
        }
        aborted{
            script{
                slackNotifier('ABORTED')
            }
        }
    }
}
