version: '2'

services:
  ctb-wkr-contavirtualest:
    build: .
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: http://10.70.30.30:9092
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://10.70.30.30:8081
      SPRING_KAFKA_CONSUMER_PROPERTIES_SCHEMA_REGISTRY_URL: http://10.70.30.30:8081
      SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL: http://10.70.30.30:8081
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_BR_COM_MACEDU: INFO
      SERVER_PORT: 8080
networks:
  default:
    external:
      name: mac-edu_kafka